version = 1

[[annotations]]
path = ["document/thesis.pdf"]
SPDX-FileCopyrightText = "Oscar Bender-Stone <oscar-bender-stone@protonmail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
  "README.md",
  ".gitignore",
  "**/.gitignore",
  "**/.python-version",
  "source/references/*.bib",
]
SPDX-FileCopyrightText = "Oscar Bender-Stone <oscar-bender-stone@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"
